{
    'name': 'Hospital Management',
    'version': '1.0.0',
    'category': 'Hospital',
    'author': 'Anjali',
    'summary': 'Hospital Management System',
    'description': """Hospital Management System""",
    'depends': ['base', 'product', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'views/menu.xml',
        'views/doctors.xml',
        'views/patient_view.xml',
        'views/pharmacy.xml',
        'views/female_patient_view.xml',
        'views/appointment_view.xml',
        'views/lab.xml',
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'sequence': -100,
}
